-- return {
--   -- add gruvbox
--   { "habamax/vim-pire" },
--
--   -- Configure LazyVim to load gruvbox
--   {
--     "LazyVim/LazyVim",
--     opts = {
--       colorscheme = "wildcharm",
--     },
--   },
-- }
