-- return {
--   {
--     "nvim-treesitter/nvim-treesitter",
--     tag = "v0.9.1",
--     opts = {
--       ensure_installed = {
--
--         "bash",
--         --"html",
--         "javascript",
--         "jsdoc",
--         "typescript",
--         "css",
--         "gitignore",
--         "graphql",
--         "http",
--         "json",
--         "scss",
--         "sql",
--         "vim",
--         "lua",
--         "markdown",
--         "markdown_inline",
--         "python",
--         "query",
--         "regex",
--         "tsx",
--         "vim",
--         "yaml",
--         "tmux",
--       },
--       auto_install = true,
--       query_linter = {
--         enable = true,
--         use_virtual_text = true,
--         lint_events = { "BufWrite", "CursorHold" },
--       },
--       highlight = {
--         enable = true,
--         disable = function(lang, buf)
--           if lang == "html" then
--             return true
--           end
--         end,
--       },
--     },
--   },
-- }
